packages:
  - './docs'
  - './apps/*'
  - './packages/**/*'
  - './utils/*'
  - './examples/*'
catalog:
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-router': ^1.130.2
  '@tanstack/react-router-devtools': ^1.130.2
  '@tanstack/react-router-with-query': ^1.130.2
  '@tanstack/react-start': ^1.130.2
  '@tanstack/router-plugin': ^1.121.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.3.4
  jsdom: ^26.0.0
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.8
  typescript: ^5.7.2
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.2
  web-vitals: ^4.2.4
